### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by ConAntonakos** [auth0-blog/hapi-jwt-authentication#1]
Hi! Thanks for the article and tutorial.

Unfortunately, I'm getting this error when attempting to execute `node server.js`:

```
/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
```

**Comment by chenkie** [comment]
Hey! Looks like it might be an issue with Mongo. Do you have MongoDB installed and running?

**Comment by ConAntonakos** [comment]
That was silly of me to not realize. Thanks, @chenkie.

**Comment by chenkie** [comment]
No prob!
